apiVersion: "operators.coreos.com/v1"
kind: "CatalogSource"
metadata:
  name: "redhat-operators"
  namespace: "openshift-marketplace"
spec:
  sourceType: grpc
  image: registry.redhat.io/redhat/redhat-operator-index:v4.6
  displayName: "Red Hat Operators"
  publisher: "Red Hat"
  updateStrategy:
    registryPoll:
      interval: 10m
